#!/usr/bin/env bash

if [ -z "$1" ]; then
	echo "Missing argument (commit message). Did you try to run this manually?"
	exit 1
fi

commitTitle="$(cat $1 | head -n1)"

# ignore merge requests
if echo "$commitTitle" | grep -qE "^Merge branch '.*"; then
	echo "Commit hook: ignoring branch merge"
	exit 0
fi

url="$(git remote get-url origin | sed 's/\.git/#commit-messages/')"

# check semantic versioning scheme
if ! echo "$commitTitle" | grep -qE '^(chore|fix|feat)\([a-z0-9\/-]+\)\s?:\s?[A-Z0-9-]+.*$'; then
	echo "Your commit title did not follow commit rules: $commitTitle"
	echo "Please see .git/hooks/commit-msg"
	exit 1
fi
