###################################################
# EDC Postgres Configuration for EDC Controlplane #
###################################################
postgresql:
  image:
    tag: "14.4.0-debian-11-r21"
  auth:
    postgresPassword: <path:traceability-foss/data/dev/edc/database#password>
    password: <path:traceability-foss/data/dev/edc/database#password>
    username: edc
    database: edc
  primary:
    resources:
      limits:
        cpu: 1.5
        memory: 1.5Gi
    persistence:
      size: 8Gi

##################################
# EDC Controlplane Configuration #
##################################
edc-controlplane:
  image:
    repository: "ghcr.io/catenax-ng/product-edc/edc-controlplane-postgresql-hashicorp-vault"
    tag: "0.1.2"

  securityContext:
    readOnlyRootFilesystem: false

  ingresses:
    - enabled: true
      hostname: "trace-x-edc.dev.demo.catena-x.net"
      annotations:
        nginx.ingress.kubernetes.io/ssl-passthrough: "false"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      endpoints:
        - ids
        - data
      className: "nginx"
      tls:
        secretName: "tls-secret"
        enabled: true

  opentelemetry:
    properties: |-
      otel.javaagent.enabled=false
      otel.javaagent.debug=true

  configuration:
    properties: |-
      edc.api.auth.key=<path:traceability-foss/data/dev/edc/controlplane#edc.api.control.auth.apikey.value>

      ids.webhook.address=https://trace-x-edc.dev.demo.catena-x.net
      edc.ids.id=urn:connector:edc-provider-controlplane
      edc.ids.catalog.id=urn:catalog:default
      edc.ids.endpoint=https://trace-x-edc.dev.demo.catena-x.net/api/v1/ids
      edc.ids.endpoint.audience=https://trace-x-edc.dev.demo.catena-x.net/api/v1/ids/data

      edc.receiver.http.endpoint=http://tracex-edc-provider-edc-controlplane:8080/api/service/pull

      edc.transfer.dataplane.sync.endpoint=http://tracex-edc-provider-edc-dataplane:8185/api/public
      edc.transfer.proxy.endpoint=https://trace-x-edc-dataplane.dev.demo.catena-x.net/api/public/
      edc.transfer.proxy.token.signer.privatekey.alias=token-signer-cert-key-dev
      edc.transfer.proxy.token.verifier.publickey.alias=token-signer-cert-dev

      edc.dataplane.selector.consumer.url=http://tracex-edc-provider-edc-dataplane:9999/api/dataplane/control
      edc.dataplane.selector.consumer.sourcetypes=HttpData
      edc.dataplane.selector.consumer.destinationtypes=HttpProxy
      edc.dataplane.selector.consumer.properties={ "publicApiUrl": "http://tracex-edc-provider-edc-dataplane:8185/api/public/" }

      edc.oauth.client.id=60:99:BC:FC:9B:F9:5D:58:C4:94:1D:02:65:3E:88:B6:F9:C7:23:B3:keyid:60:99:BC:FC:9B:F9:5D:58:C4:94:1D:02:65:3E:88:B6:F9:C7:23:B3
      edc.oauth.public.key.alias=daps-cert-edc-provider-dev
      edc.oauth.private.key.alias=daps-cert-key-edc-provider-dev
      edc.oauth.provider.audience=idsc:IDS_CONNECTORS_ALL
      edc.oauth.provider.jwks.url=https://daps1.int.demo.catena-x.net/.well-known/jwks.json
      edc.oauth.token.url=https://daps1.int.demo.catena-x.net/token

      edc.vault.hashicorp.url=https://vault.demo.catena-x.net
      edc.vault.hashicorp.token=<path:traceability-foss/data/dev/edc#edc.vault.hashicorp.token>
      edc.vault.hashicorp.timeout.seconds=30
      edc.vault.hashicorp.health.check.enabled=true
      edc.vault.hashicorp.health.check.standby.ok=true
      edc.vault.hashicorp.api.secret.path=/v1/traceability-foss

      edc.data.encryption.keys.alias=edc-data-encryption-keys-alias
      edc.data.encryption.algorithm=NONE

      # Postgresql related configuration
      edc.datasource.asset.name=asset
      edc.datasource.asset.url=jdbc:postgresql://tracex-edc-provider-postgresql-hl:5432/edc
      edc.datasource.asset.user=edc
      edc.datasource.asset.password=<path:traceability-foss/data/dev/edc/database#password>
      edc.datasource.contractdefinition.name=contractdefinition
      edc.datasource.contractdefinition.url=jdbc:postgresql://tracex-edc-provider-postgresql-hl:5432/edc
      edc.datasource.contractdefinition.user=edc
      edc.datasource.contractdefinition.password=<path:traceability-foss/data/dev/edc/database#password>
      edc.datasource.contractnegotiation.name=contractnegotiation
      edc.datasource.contractnegotiation.url=jdbc:postgresql://tracex-edc-provider-postgresql-hl:5432/edc
      edc.datasource.contractnegotiation.user=edc
      edc.datasource.contractnegotiation.password=<path:traceability-foss/data/dev/edc/database#password>
      edc.datasource.policy.name=policy
      edc.datasource.policy.url=jdbc:postgresql://tracex-edc-provider-postgresql-hl:5432/edc
      edc.datasource.policy.user=edc
      edc.datasource.policy.password=<path:traceability-foss/data/dev/edc/database#password>
      edc.datasource.transferprocess.name=transferprocess
      edc.datasource.transferprocess.url=jdbc:postgresql://tracex-edc-provider-postgresql-hl:5432/edc
      edc.datasource.transferprocess.user=edc
      edc.datasource.transferprocess.password=<path:traceability-foss/data/dev/edc/database#password>

###############################
# EDC Dataplane Configuration #
###############################
edc-dataplane:
  image:
    repository: "ghcr.io/catenax-ng/product-edc/edc-dataplane-hashicorp-vault"
    tag: "0.1.2"

  securityContext:
    readOnlyRootFilesystem: false

  ingresses:
    - enabled: true
      hostname: "trace-x-edc-dataplane.dev.demo.catena-x.net"
      annotations:
        nginx.ingress.kubernetes.io/ssl-passthrough: "false"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      endpoints:
        - public
      className: "nginx"
      tls:
        enabled: true
        secretName: "tls-secret"

  opentelemetry:
    properties: |-
      otel.javaagent.enabled=false

  configuration:
    properties: |-
      edc.dataplane.token.validation.endpoint=http://tracex-edc-provider-edc-controlplane:8182/validation/token

      # TODO: check backend url
      edc.receiver.http.endpoint=http://tracex-irs-aaswrapper:9192/callback/endpoint-data-reference

      edc.oauth.client.id=60:99:BC:FC:9B:F9:5D:58:C4:94:1D:02:65:3E:88:B6:F9:C7:23:B3:keyid:60:99:BC:FC:9B:F9:5D:58:C4:94:1D:02:65:3E:88:B6:F9:C7:23:B3
      edc.oauth.public.key.alias=daps-cert-dev
      edc.oauth.private.key.alias=daps-cert-key-dev
      edc.oauth.provider.audience=idsc:IDS_CONNECTORS_ALL
      edc.oauth.provider.jwks.url=https://daps1.int.demo.catena-x.net/.well-known/jwks.json
      edc.oauth.token.url=https://daps1.int.demo.catena-x.net/token

      edc.vault.hashicorp.url=https://vault.demo.catena-x.net
      edc.vault.hashicorp.token=<path:traceability-foss/data/dev/edc#edc.vault.hashicorp.token>
      edc.vault.hashicorp.timeout.seconds=30
      edc.vault.hashicorp.health.check.enabled=true
      edc.vault.hashicorp.health.check.standby.ok=true
      edc.vault.hashicorp.api.secret.path=/v1/traceability-foss
