name: "Eclipse DASH IP Check"

on:
  workflow_dispatch: # Trigger manually
  push:
    branches-ignore:
      - 'main'
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  pull_request:
    branches: main
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - 'api/**'
      - 'api-tests/**'
      - 'charts/**'
      - 'ci/**'
      - 'docs/**'
      - 'dev/**'
      - 'testdata-transform/**'
      - 'testing/**'
      - 'uml-diagrams/**'
      - 'README.md'
      - 'CHANGELOG.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven and check dependencies
        run: |
          mvn --quiet --batch-mode --update-snapshots verify -Ddash.summary=DEPENDENCIES -DskipTests -Pdependency-check
      - name: upload results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          path: 'DEPENDENCIES'
